Install git instead of git-core with MacPorts
`sudo port install git +svn +doc +bash_completion +gitweb` succeeds, whereas `sudo port install git-core +svn +doc +bash_completion +gitweb` fails with output that includes the following helpful messages:
Error: git-core has been made obsolete by the port git. Please install git instead.
Error: org.macports.configure for port git-core returned: obsolete port
Please see the log file for port git-core for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_devel_git-core/git-core/main.log
Error: Processing of port git-core failed